"""Added settings

Revision ID: 4127d08610dd
Revises: 569a3336d37a
Create Date: 2026-03-04 17:20:22.527498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4127d08610dd'
down_revision: Union[str, Sequence[str], None] = '569a3336d37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_locale_overrides_locale_key'), table_name='locale_overrides')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_locale_overrides_locale_key'), 'locale_overrides', ['locale', 'key'], unique=1)
    # ### end Alembic commands ###
